apiVersion: v1
kind: Service
metadata:
  name: devops-integration-service
spec:
  selector:
    app: devops-integration-k8s
  ports:
    - protocol: "TCP"
      port: 9070
      targetPort: 9070
  type: NodePort
           
    
  
  

